sudo: false
language: node_js
node_js:
  - stable
  - 6
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
script:
  - npm test
notifications:
  slack: godofchicken:BqRKwRJXLp7VjtggROq6riqm
